# -*- coding: utf-8 -*-
"""
/***************************************************************************
 showSameOpposite
                                 A QGIS plugin
 showSameOpposite
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-04-17
        copyright            : (C) 2025 by showSameOpposite
        email                : showSameOpposite
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load showSameOpposite class from file showSameOpposite.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .showSameOpposite import showSameOpposite

    return showSameOpposite(iface)
